FORMAT: 1A

# simplepayments-app

## Payment Services Collection [/service]

Список платежных сервисов для главного экрана

### List All services [GET]

+ Response 200 (application/json)

        [
            {
                "id": "gas",
                "name": "Газоснабжение",
                "image": "https://neonxp.ru/img/gas.png",
                "_links": [
                    {"href": "/search/gas", "rel": "search"}                
                ]
            },
            {
                "id": "capital_repair",
                "name": "Капитальный ремонт",
                "image": "https://neonxp.ru/img/kr.png",
                "_links": [
                    {"href": "/search/capital_repair", "rel": "search"}
                ]
            },
            {
                "id": "jkh",
                "name": "ЖКХ",
                "image": "https://neonxp.ru/img/jkh.png",
                "_links": [
                    {"href": "/search/jkh", "rel": "search"}
                ]
            },
            {
                "id": "gibdd",
                "name": "Штрафы ГИБДД",
                "image": "https://neonxp.ru/img/gibdd.png",
                "_links": [
                    {"href": "/search/gibdd", "rel": "search"},
                    {"href": "/schema/search/gibdd", "rel": "schema"}
                ]
            },
            {
                "id": "fssp",
                "name": "Судебные приставы",
                "image": "https://neonxp.ru/img/fssp.png",
                "_links": [
                    {"href": "/search/fssp", "rel": "search"}
                ]
            },
            {
                "id": "fns",
                "name": "Налоги",
                "image": "https://neonxp.ru/img/nalog.png",
                "_links": [
                    {"href": "/search/fns", "rel": "search"}
                ]
            }
        ]
        
## Group Капитальный ремонт

### Schema формы поиска [GET /schema/search/capital_repair.json]

+ Response 200 (application/json)

        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "required": ["region_id", "ls_or_address"],
            "properties": {
                "region_id": {
                    "type": "string",
                    "label": "Регион",
                    "placeholder": "Выберите регион",
                    "meta" : "region"
                },
                "ls_or_address": {
                    "type": "string",
                    "label": "Лицевой счет или адрес",
                    "placeholder": "Введите номер ЛС или адрес"
                }
            }
        }

### Поиск [POST /search/capital_repair]

+ Request (application/json)

        [
            {
                "document_type": "capital_repair_requisite", 
                "document_value": {
                    "region_id": 16,
                    "ls_or_address": 234
                } 
            }
        ]


+ Response 200 (application/json)

        [
            {
                "document_type": "capital_repair_requisite", 
                "document_value": {
                    "region_id": 16,
                    "ls_or_address": 234
                },
                "accurals": [
                    {
                        "uin": "some_our_uin",
                        "account": "ls_num_here",
                        "sum": 1321.12,
                        "date": "2018-01-19 00:00:00",
                        "description": null,
                        "additional_fields": {
                            "operator_name": "Фонд капитального ремонта многоквартирных домов Томской области",
                            "address": "420094, Казань, ул. Голубятникова 26а, 39",
                            "floor_square": 55.5,
                            "tariff": 12
                        },
                        "_links": [
                            {"href": "/helper/capital_repair/division/123", "rel": "division"}
                        ]
                    }
                ]
            }
        ]
        
### Schema формы оплаты [GET /schema/payment/capital_repair.json]

+ Response 200 (application/json)

        {
            "type": "object",
            "required": ["uin", "payer_fullname", "payment_sum"],
            "properties": {
                "uin": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "payer_fullname": {
                    "type": "string",
                    "label": "ФИО плательщика",
                    "placeholder": "Фамилия Имя Отчество"
                },
                "email": {
                    "type": "string",
                    "label": "Email для получения квитанции",
                    "placeholder": "mail@example.com"
                },
                "payment_sum": {
                    "type": "number",
                    "label": "Сумма оплаты"
                }
            }
        }

### Форма оплаты [POST /payment/capital_repair]

+ Request (application/json)

        {
            "uin": ["some_our_uin"],
            "payer_fullname": "Андреев Ростислав Анатольевич",
            "email": "someemail@gmail.com",
            "payment_sum": 550.2
        }
        
+ Response 200 (application/json)

        {
            "order_id": "hash_string",
            "sum": 1000,
            "fee": 125,
            "form_url": "https://service.moneta.ru/assistant.widget?MNT_ID=66271719&MNT_TRANSACTION_ID=5afaacbbef9f7&MNT_CURRENCY_CODE=RUB&MNT_AMOUNT=565.00&MNT_DESCRIPTION=Задолженность ФССП&MNT_TEST_MODE=0&MNT_SIGNATURE=e03b22e5d7477be7f296a42a0667ad26&MNT_SUCCESS_URL=https://gos-oplata.ru/fssp-payment/success&MNT_FAIL_URL=https://gos-oplata.ru/fssp-payment/fail&MNT_PAY_SYSTEM=payanyway&MNT_IS_REGULAR=&MNT_FORM_METHOD=POST&followup=true"
        }

## Group Газоснабжение

### Список поставщиков в регионе [GET /search/gas/{region_id}]

+ Parameters
    + region_id (nubmer) - ID региона из справочника
    
+ Response 200 (application/json)

        [
            {
                "id": 100500,
                "name": "ООО ПетроГазСнаб"
            },
            {
                "id": 100501,
                "name": "АО Газпром"
            }
        ]
    
### Schema формы поиска [GET /schema/search/gas.json]

+ Response 200 (application/json)

        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "required": ["region_id", "provider_id", "ls"],
            "properties": {
                "region_id": {
                    "type": "string",
                    "label": "Регион",
                    "placeholder": "Выберите регион",
                    "meta" : "region"
                },
                "provider_id": {
                    "type": "string",
                    "label": "Поставщик",
                    "placeholder": "Выберите поставщика",
                    "meta" : "provider"
                },
                "ls": {
                    "type": "string",
                    "placeholder": "Укажите номер лицевого счета",
                    "label": "Номер лицевого счета"
                }
            }
        }

### Поиск [POST /search/gas]

+ Request (application/json)

        [
            {
                "document_type": "ls_requisite", 
                "document_value": {
                    "region_id": 16,
                    "provider_id": 234,
                    "ls": 3123123
                } 
            }
        ]


+ Response 200 (application/json)

        [
            {
                "document_type": "ls_requisite", 
                "document_value": {
                    "region_id": 16,
                    "provider_id": 234,
                    "ls": 3123123
                },
                "accurals": [
                    {
                        "uin": "some_our_uin",
                        "account": "3123123",
                        "sum": 1321.12,
                        "date": "2018-01-19 00:00:00",
                        "description": null,
                        "additional_fields": {
                            "address": "420094, Казань, ул. Голубятникова 26а, 39"
                        },
                        "_links": [
                            {"href": "/helper/gas/division/123", "rel": "division"}
                        ]
                    }
                ]
            }
        ]
        
### Schema формы оплаты [GET /schema/payment/gas.json]

+ Response 200 (application/json)

        {
            "type": "object",
            "required": ["uin", "payer_fullname", "payment_sum"],
            "properties": {
                "uin": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "payer_fullname": {
                    "type": "string",
                    "label": "ФИО плательщика",
                    "placeholder": "Фамилия Имя Отчество"
                },
                "email": {
                    "type": "string",
                    "label": "Email для получения квитанции",
                    "placeholder": "mail@example.com"
                },
                "counter_value": {
                    "type": "number",
                    "label": "Показания счетчика",
                    "placeholder": "0000,00"
                },
                "date": {
                    "type": "string",
                    "label": "На дату",
                    "placeholder": "00.00.0000"
                },
                "payment_sum": {
                    "type": "number",
                    "label": "Сумма оплаты"
                }
            }
        }

### Форма оплаты [POST /payment/gas]

+ Request (application/json)

        {
            "uin": ["some_our_uin"],
            "payer_fullname": "Андреев Ростислав Анатольевич",
            "email": "someemail@gmail.com",
            "counter_value": 257.24,
            "date": "2018-09-07",
            "payment_sum": 550.2
        }
        
+ Response 200 (application/json)

        {
            "order_id": "hash_string",
            "sum": 1000,
            "fee": 125,
            "form_url": "https://service.moneta.ru/assistant.widget?MNT_ID=66271719&MNT_TRANSACTION_ID=5afaacbbef9f7&MNT_CURRENCY_CODE=RUB&MNT_AMOUNT=565.00&MNT_DESCRIPTION=Задолженность ФССП&MNT_TEST_MODE=0&MNT_SIGNATURE=e03b22e5d7477be7f296a42a0667ad26&MNT_SUCCESS_URL=https://gos-oplata.ru/fssp-payment/success&MNT_FAIL_URL=https://gos-oplata.ru/fssp-payment/fail&MNT_PAY_SYSTEM=payanyway&MNT_IS_REGULAR=&MNT_FORM_METHOD=POST&followup=true"
        }
        
## Group ЖКХ

### Список поставщиков в регионе [GET /search/jkh/{region_id}]

+ Parameters
    + region_id (nubmer) - ID региона из справочника
    
+ Response 200 (application/json)

        [
            {
                "id": 100500,
                "name": "УК Уютный Дом"
            },
            {
                "id": 100501,
                "name": "УК УправГлавСнаб"
            }
        ]
    
### Schema формы поиска [GET /schema/search/jkh.json]

+ Response 200 (application/json)

        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "required": ["region_id", "provider_id", "ls"],
            "properties": {
                "region_id": {
                    "type": "string",
                    "label": "Регион",
                    "placeholder": "Выберите регион",
                    "meta" : "region"
                },
                "operator_id": {
                    "type": "string",
                    "label": "Управляющая организация",
                    "placeholder": "Выберите поставщика услуг",
                    "meta" : "operator"
                },
                "ls": {
                    "type": "string",
                    "placeholder": "Укажите номер лицевого счета",
                    "label": "Номер лицевого счета"
                }
            }
        }

### Поиск [POST /search/jkh]

+ Request (application/json)

        [
            {
                "document_type": "ls_requisite", 
                "document_value": {
                    "region_id": 16,
                    "operator_id": 234,
                    "ls": 3123123
                } 
            }
        ]


+ Response 200 (application/json)

        [
            {
                "document_type": "ls_requisite", 
                "document_value": {
                    "region_id": 16,
                    "operator_id": 234,
                    "ls": 3123123
                },
                "accurals": [
                    {
                        "uin": "some_our_uin",
                        "account": "3123123",
                        "sum": 1321.12,
                        "date": "2018-01-19 00:00:00",
                        "description": null,
                        "additional_fields": {
                            "address": "420094, Казань, ул. Голубятникова 26а, 39",
                            "floor_square": 55.5
                        },
                        "_links": [
                            {"href": "/helper/gas/division/123", "rel": "division"}
                        ]
                    }
                ]
            }
        ]
        
### Schema формы оплаты [GET /schema/payment/jkh.json]

+ Response 200 (application/json)

        {
            "type": "object",
            "required": ["uin", "payer_fullname", "payment_sum"],
            "properties": {
                "uin": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "payer_fullname": {
                    "type": "string",
                    "label": "ФИО плательщика",
                    "placeholder": "Фамилия Имя Отчество"
                },
                "email": {
                    "type": "string",
                    "label": "Email для получения квитанции",
                    "placeholder": "mail@example.com"
                },
                "payment_sum": {
                    "type": "number",
                    "label": "Сумма оплаты"
                }
            }
        }

### Форма оплаты [POST /payment/jkh]

+ Request (application/json)

        {
            "uin": ["some_our_uin"],
            "payer_fullname": "Андреев Ростислав Анатольевич",
            "email": "someemail@gmail.com",
            "payment_sum": 550.2
        }
        
+ Response 200 (application/json)

        {
            "order_id": "hash_string",
            "sum": 1000,
            "fee": 125,
            "form_url": "https://service.moneta.ru/assistant.widget?MNT_ID=66271719&MNT_TRANSACTION_ID=5afaacbbef9f7&MNT_CURRENCY_CODE=RUB&MNT_AMOUNT=565.00&MNT_DESCRIPTION=Задолженность ФССП&MNT_TEST_MODE=0&MNT_SIGNATURE=e03b22e5d7477be7f296a42a0667ad26&MNT_SUCCESS_URL=https://gos-oplata.ru/fssp-payment/success&MNT_FAIL_URL=https://gos-oplata.ru/fssp-payment/fail&MNT_PAY_SYSTEM=payanyway&MNT_IS_REGULAR=&MNT_FORM_METHOD=POST&followup=true"
        }

## Group ГИБДД

### Schema формы поиска [GET /schema/search/gibdd.json]

+ Response 200 (application/json)

        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "oneOf":[
                {"required": ["vu"]},
                {"required": ["ctc"]}
            ],
            "properties": {
                "vu": {
                    "type": "string",
                    "label": "Водительское удостоверение"
                    
                },
                "ctc": {
                    "type": "string",
                    "label": "СТС"
                    
                }
            }
        }

### Поиск [POST /search/gibdd]

+ Request (application/json)

        [
            {"document_type": "vu", "document_value": "73УВ123654"},
            {"document_type": "uin", "document_value": "18810119180119001127"},
            {"document_type": "ctc", "document_value": "1612123123"}
        ]

+ Response 200 (application/json)

        [
            {                
                "document_type": "vu",
                "document_value": "73УВ123654",
                "accurals": null
            },
            {
                "document_type": "uin",
                "document_value": "18810119180119001127",
                "accurals": [
                    {
                        "uin": "18810119180119001127",
                        "account": "18810119180119001127",
                        "sum": 1000,
                        "date": "2018-01-19 00:00:00",
                        "description": "Оплата штрафа ГИБДД УИН 18810119180119001127 от 19.01.2018",
                        "additional_fields": {
                            "koap_code": null,
                            "koap_text": null,
                            "kbk": "18811630020016000140",
                            "discount_until": "2018-02-08 00:00:00"
                        },
                        "_links": [
                            {"href": "/helper/gibdd/division/123", "rel": "division"},
                            {"href": "/gibdd/images/18810119180119001127", "rel": "images"}
                        ]
                    }
                ]
            },
            {
                "document_type": "ctc",
                "document_value": "1646256659",
                "accurals": [
                    {
                        "uin": "18810173180824058236",
                        "account": "18810173180824058236",
                        "sum": 500,
                        "date": "2018-08-24 00:00:00",
                        "description": "Оплата штрафа ГИБДД УИН 18810173180824058236 от 24.08.2018",
                        "additional_fields": {
                            "koap_code": "12.9Ч.2",
                            "koap_text": "ПРЕВЫШЕНИЕ УСТАНОВЛЕННОЙ СКОРОСТИ ДВИЖЕНИЯ ТРАНСПОРТНОГО СРЕДСТВА НА ВЕЛИЧИНУ БОЛЕЕ 20, НО НЕ БОЛЕЕ 40 КМ/Ч",
                            "kbk": "18811630020016000140",
                            "discount_enabled": true,
                            "discount_until": "2018-09-13 00:00:00"
                        },
                        "_links": [
                            {"href": "/helper/gibdd/division/123", "rel": "division"},
                            {"href": "/gibdd/images/18810119180119001127", "rel": "images"}
                        ]
                    }
                ]
            }
        ]
        
### Фотографии [GET /gibdd/images/18810119180119001127]

+ Response 200 (application/json)

        [
            "https://xn--80aadhgazu0ak9a.xn--p1ai/fine_photo/18810110180517002950_0.jpg", 
            "https://xn--80aadhgazu0ak9a.xn--p1ai/fine_photo/18810110180517002950_1.jpg"
        ]

### Schema формы оплаты [GET /schema/payment/gibdd.json]

+ Response 200 (application/json)

        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "required": ["uin", "payer_fullname"],
            "properties": {
                "uin": {
                    "type": "array",
                    "label": "УИН",
                    "items": {
                        "type": "string"
                    }
                },
                "payer_fullname": {
                    "type": "string",
                    "label": "ФИО Водителя",
                    "placeholder": "Фамилия Имя Отчество"
                },
                "email": {
                    "type": "string",
                    "label": "Email для получения квитанции",
                    "placeholder": "mail@example.com"
                }
            }
        }

### Форма оплаты [POST /payment/gibdd]

+ Request (application/json)

        {
            "uin": ["18810116180312243747", "18810116180312243759"],
            "payer_fullname": "Бикмухаметов Рустэм Яник"
        }
    
+ Response 200 (application/json)

        {
            "order_id": "hash_string",
            "sum": 1000,
            "fee": 125,
            "form_url": "https://service.moneta.ru/assistant.widget?MNT_ID=66271719&MNT_TRANSACTION_ID=5afaacbbef9f7&MNT_CURRENCY_CODE=RUB&MNT_AMOUNT=565.00&MNT_DESCRIPTION=Оплата штрафа ГИБДД&MNT_TEST_MODE=0&MNT_SIGNATURE=e03b22e5d7477be7f296a42a0667ad26&MNT_SUCCESS_URL=https://gos-oplata.ru/fssp-payment/success&MNT_FAIL_URL=https://gos-oplata.ru/fssp-payment/fail&MNT_PAY_SYSTEM=payanyway&MNT_IS_REGULAR=&MNT_FORM_METHOD=POST&followup=true"
        }

### Часто задаваемые вопросы [GET /gibdd/help]

+ Response 200 (application/json)

        [
            {
                "question": "Как оплатить штраф ГИБДД?",
                "answer": "Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n "
            },
            {
                "question": "Как оплатить штраф ГИБДД?",
                "answer": "Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n "
            },
            {
                "question": "Как оплатить штраф ГИБДД?",
                "answer": "Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n "
            },
            {
                "question": "Как оплатить штраф ГИБДД?",
                "answer": "Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n "
            },
            {
                "question": "Как оплатить штраф ГИБДД?",
                "answer": "Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n "
            },
            {
                "question": "Как оплатить штраф ГИБДД?",
                "answer": "Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n "
            },
            {
                "question": "Как оплатить штраф ГИБДД?",
                "answer": "Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n Some text \b\n "
            }
            
        ]

## Group ФССП

### Schema формы поиска [GET /schema/search/fssp.json]

+ Response 200 (application/json)

        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "properties": {
                "region_id": {
                    "type": "string",
                    "label": "Регион",
                    "meta": "region"
                },
                "fio": {
                    "type": "string",
                    "label": "ФИО должника"
                },
                "birthdate": {
                    "type": "string",
                    "help": "Введите паспортные данные должника",
                    "label": "Дата рождения",
                    "pattern": "\\d{2}\\.\\d{2}\\.\\d{4}"
                }
            },
            "required": [
                "region_id",
                "fio",
                "birthdate"
            ]
        }

### Поиск [POST /search/fssp]

+ Request (application/json)

        [
            {
                "document_type": "fssp_requisite", 
                "document_value": {
                    "region_id": 15,
                    "fio": "Иванов Петр Степанович",
                    "birthdate": "2001.02.10"
                }
            }
        ]
    
+ Response 200 (application/json)

        [
            {
                "document_type": "fssp_requisite", 
                "document_value": {
                    "region_id": 15,
                    "fio": "Иванов Петр Степанович",
                    "birthdate": "2001.02.10"
                },
                "accurals": [
                    {
                        "uin": "32216008150065046004",
                        "account": "65046/15/16008-ИП",
                        "sum": 25500.56,
                        "date": "2018-08-24 00:00:00",
                        "description": "Задолженность по налогам и сборам",
                        "additional_fields": null,
                        "_links": [
                            {"href": "/helper/fssp/division/16008", "rel": "division"}
                        ]
                    }
                ]
            },
            {
                "document_type": "passport",
                "document_value": "730867568",
                "accurals": null
            }
        ]
        
### Schema формы оплаты [GET /schema/payment/fssp.json]

+ Response 200 (application/json)

        {
            "type": "object",
            "required": ["uin"],
            "properties": {
                "uin": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "email": {
                    "type": "string"
                }
            }
        }

### Форма оплаты [POST /payment/fssp]

+ Request (application/json)

        {
            "uin": ["32216008150065046004"],
            "email": "some@mail.ru"
        }
    
+ Response 200 (application/json)

        {
            "order_id": "hash_string",
            "sum": 1000,
            "fee": 125,
            "form_url": "https://service.moneta.ru/assistant.widget?MNT_ID=66271719&MNT_TRANSACTION_ID=5afaacbbef9f7&MNT_CURRENCY_CODE=RUB&MNT_AMOUNT=565.00&MNT_DESCRIPTION=Задолженность ФССП&MNT_TEST_MODE=0&MNT_SIGNATURE=e03b22e5d7477be7f296a42a0667ad26&MNT_SUCCESS_URL=https://gos-oplata.ru/fssp-payment/success&MNT_FAIL_URL=https://gos-oplata.ru/fssp-payment/fail&MNT_PAY_SYSTEM=payanyway&MNT_IS_REGULAR=&MNT_FORM_METHOD=POST&followup=true"
        }

## Group ФНС 

### Schema формы поиска [GET /schema/search/fns.json]

+ Response 200 (application/json)

        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "oneOf":[
                {"required": ["uin"]},
                {"required": ["inn"]}
            ],
            "properties": {
                "uin": {
                    "type": "string",
                    "label": "УИН"
                },
                "inn": {
                    "type": "string",
                    "label": "ИНН"
                }
            }
        }

### Поиск [POST /search/fns]

+ Request (application/json)

        [
            {"document_type": "inn", "document_value": "156465465465"}
        ]
    
+ Response 200 (application/json)

        [
            {
                "document_type": "inn", 
                "document_value": "156465465465",
                "accurals": [
                    {
                        "uin": "18214328150065046004",
                        "account": null,
                        "sum": 4500,
                        "date": "2018-08-24 00:00:00",
                        "description": "Транспортный налог",
                        "additional_fields": null,
                        "_links": [
                            {"href": "/helper/fssp/division/16008", "rel": "division"}
                        ]
                    }
                ]
            }
        ]
        
### Schema формы оплаты [GET /schema/payment/fns.json]

+ Response 200 (application/json)

        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "required": ["uin"],
            "properties": {
                "uin": {
                    "type": "array",
                    "label": "УИН",
                    "items": {
                        "type": "string"
                    }
                },
                "email": {
                    "type": "string",
                    "label": "Email для получения квитанции",
                    "placeholder": "mail@example.com"
                }
            }
        }

### Форма оплаты [POST /payment/fns]

+ Request (application/json)

        {
            "uin": ["32216008150065046004"],
            "email": "asd@mnail.ru"
        }
    
+ Response 200 (application/json)

        {
            "order_id": "hash_string",
            "sum": 1000,
            "fee": 125,
            "form_url": "https://service.moneta.ru/assistant.widget?MNT_ID=66271719&MNT_TRANSACTION_ID=5afaacbbef9f7&MNT_CURRENCY_CODE=RUB&MNT_AMOUNT=565.00&MNT_DESCRIPTION=Оплата штрафа ГИБДД&MNT_TEST_MODE=0&MNT_SIGNATURE=e03b22e5d7477be7f296a42a0667ad26&MNT_SUCCESS_URL=https://gos-oplata.ru/fssp-payment/success&MNT_FAIL_URL=https://gos-oplata.ru/fssp-payment/fail&MNT_PAY_SYSTEM=payanyway&MNT_IS_REGULAR=&MNT_FORM_METHOD=POST&followup=true"
        }


## История оплат [GET /payment/history]

+ Response 200 (application/json)

        [
            {
                "payment_date": "2018-09-23",
                "accurals": [
                    {
                        "title": "Штраф ГИБДД",
                        "description": "Оплата штрафа ГИБДД УИН 18810177180808648716 от 19.08.2018",
                        "sum": 500,
                        "receipt_url": "https://xn--80aadhgazu0ak9a.xn--p1ai/gibdd-payment/receipt?fine_id=336715"
                    }
                ]
            }
        ]

## Group Справочники

### Коды регионов [GET /helper/region]

+ Response 200 (application/json)

        [
            {"id": 77, "name": "Москва"},
            {"id": 16, "name": "Республика Татарстан (Татарстан)"},
            {"id": 14, "name": "Республика Саха (Якутия)"}
        ]

### Подразделениe ГИБДД [GET /helper/gibdd/division/123]

+ Response 200 (application/json)

        {
            "division_id": 123,
            "name": "Специализированный отдел регистрации и государственного технического осмотра АМТС, экзаменационной работы ЦСН БДД МВД России",
            "code": "1100103",
            "address": "г Москва, Ленинградское шоссе, д 59",
            "post_index": "125195",
            "region_code": "77",
            "bik": "044525000",
            "bank_name": "ГУ Банка России по ЦФО",
            "rs": "40101810045250010041",
            "receiver_name": "04731506780 в УФК по г.Москве",
            "inn": "5040102985",
            "kpp": "773001001",
            "oktmo": "45342000",
            "is_active": true
        }

### Подразделение ФССП [GET /helper/fssp/division/16008]

+ Response 200 (application/json)

        {
            "code": 16008,
            "region": 16,
            "name": "Межрайонный отдел судебных приставов по особо важным исполнительным производствам",
            "recv_name": "УФК по Республике Адыгея (МОСП УФССП России по Республике Адыгея Л/С 05761829840)",
            "bank": "ГРКЦ НБ РЕСП. АДЫГЕЯ БАНКА РОССИИ",
            "cnt": "40302810100001000015",
            "bik": "047908001",
            "inn": "0105043869",
            "kpp": "010545003",
            "okato": "79401000000",
            "oktmo": "79701000",
            "ls": "05761829840"
        }
        
### Оператор капремонта [GET /helper/capital_repair/division/123]

+ Response 200 (application/json)

        {
            "id": 16008,
            "region": 16,
            "name": "Фонд капитального ремонта многоквартирных домов Томской области",
            "recv_name": "УФК по Республике Адыгея (МОСП УФССП России по Республике Адыгея Л/С 05761829840)",
            "bank": "ГРКЦ НБ РЕСП. АДЫГЕЯ БАНКА РОССИИ",
            "cnt": "40302810100001000015",
            "bik": "047908001",
            "inn": "0105043869",
            "kpp": "010545003",
            "okato": "79401000000",
            "oktmo": "79701000",
            "ls": "05761829840"
        }